# Generated by `dnsctl import-blocks`. Adopts the records Cloudflare
# already serves, so that the first apply changes no DNS data.
#
# Keyed by zone and selected with var.zone, because the root module owns
# one zone at a time. An import block naming another zone's records would
# be active while planning this one.
#
# One `import` block with for_each, rather than one block per record.
# Repeated blocks targeting instances of the same resource inside a module
# were observed to apply only the first and silently ignore the rest:
# fifteen blocks produced `1 to import, 14 to add`, which would have
# duplicated the whole zone. The for_each form produced `15 to import,
# 0 to add`. Verified against Terraform 1.16.0.
#
# Generated: a list of Cloudflare record ids. Commit it for the apply that
# adopts a zone, because CI has only what is in the repository, then delete
# it. Regenerate rather than keep -- it goes stale the moment a record is
# recreated by hand.

locals {
  imports = {
    "matt-ffffff.com" = {
      "_dmarc.matt-ffffff.com|TXT|v=DMARC1; p=quarantine; sp=quarantine; rua=mailto:1174ef33290a481faf1bb5d5e4fae0e8@dmarc-reports.cloudflare.net" = "0038f23cef2a65a5c2e950c7f4c2cdc0/10238a7e2605a6ff0022dd2e2ccac903"
      "autodiscover.matt-ffffff.com|CNAME|autodiscover.outlook.com"                                                                                = "0038f23cef2a65a5c2e950c7f4c2cdc0/7c27d8c2fdc9c9275c2ff93da6ec5b52"
      "email.matt-ffffff.com|NS|ns1-03.azure-dns.com"                                                                                              = "0038f23cef2a65a5c2e950c7f4c2cdc0/ef20c33105fcf2b528ed7c901cb8a1d3"
      "email.matt-ffffff.com|NS|ns2-03.azure-dns.net"                                                                                              = "0038f23cef2a65a5c2e950c7f4c2cdc0/fa54bd7d7ab7649d8214b24e37104c50"
      "email.matt-ffffff.com|NS|ns3-03.azure-dns.org"                                                                                              = "0038f23cef2a65a5c2e950c7f4c2cdc0/62e0a4ce646930715af1d00a40079064"
      "email.matt-ffffff.com|NS|ns4-03.azure-dns.info"                                                                                             = "0038f23cef2a65a5c2e950c7f4c2cdc0/b1ddfab22784b2ce5127f5c1207b94df"
      "home.matt-ffffff.com|CNAME|5deoge71zazv0j2it4plnuyzatlbxufp.ui.nabu.casa"                                                                   = "0038f23cef2a65a5c2e950c7f4c2cdc0/78294fcd104b90883b6f479ddb7d2e00"
      "matt-ffffff.com|A|13.248.213.45"                                                                                                            = "0038f23cef2a65a5c2e950c7f4c2cdc0/54e8f63cf71c9afa525fa98593479c03"
      "matt-ffffff.com|A|76.223.67.189"                                                                                                            = "0038f23cef2a65a5c2e950c7f4c2cdc0/f5374602f0a6863d311652fb20212336"
      "matt-ffffff.com|MX|mx01.mail.icloud.com"                                                                                                    = "0038f23cef2a65a5c2e950c7f4c2cdc0/3880379be2d83bf1db0f00677c36f3e1"
      "matt-ffffff.com|MX|mx02.mail.icloud.com"                                                                                                    = "0038f23cef2a65a5c2e950c7f4c2cdc0/9b13da9a927a647301bf28c5f8feabd2"
      "matt-ffffff.com|TXT|apple-domain=o2rSMey13yFlucwo"                                                                                          = "0038f23cef2a65a5c2e950c7f4c2cdc0/363ae55c8723777cf44d97f7ed3482c4"
      "matt-ffffff.com|TXT|v=spf1 include:icloud.com ~all"                                                                                         = "0038f23cef2a65a5c2e950c7f4c2cdc0/9de02bbb22b522b1eef57606f1aebd78"
      "sig1._domainkey.matt-ffffff.com|CNAME|sig1.dkim.matt-ffffff.com.at.icloudmailadmin.com"                                                     = "0038f23cef2a65a5c2e950c7f4c2cdc0/03a8fa2ffc76213f0c32776c7268dfba"
      "www.matt-ffffff.com|CNAME|matt-ffffff.com"                                                                                                  = "0038f23cef2a65a5c2e950c7f4c2cdc0/08e08794a272631107677e21a52915a0"
    }
  }
}

import {
  for_each = try(local.imports[var.zone], {})
  to       = module.zone.cloudflare_dns_record.this[each.key]
  id       = each.value
}
